# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0004_auto_20170628_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TimeField(max_length=38),
        ),
    ]
