# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0005_auto_20170628_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(max_length=38),
        ),
    ]
