# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome_app', '0002_auto_20170428_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username_name',
            new_name='user_name',
        ),
    ]
