# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome_app', '0003_auto_20170428_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='user',
            new_name='iuser',
        ),
    ]
