# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 04:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome_app', '0004_auto_20170428_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='iuser',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='books',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
