# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welcome_app', '0005_auto_20170428_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Authors', models.CharField(max_length=30)),
                ('Title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_reviews', models.TextField(max_length=1000)),
                ('ratings', models.CharField(max_length=30)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcome_app.Books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welcome_app.User')),
            ],
        ),
    ]
