# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cost',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.IntegerField(default=10),
        ),
    ]
